version: '3'

services:
  api: 
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    depends_on:
      - database
    networks:
      - internal-network
    restart: always
  web: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - internal-network
  database:
    image: postgres
    networks:
      - internal-network
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=2553218858"
      - "POSTGRES_DB=beantest"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

networks:
  internal-network:
    driver: bridge