version: '3'

services:
  api: 
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    environment:
      TZ: "America/Sao_Paulo"
      VIRTUAL_PORT: 3333
      VIRTUAL_HOST: api.beantest.devjosuehub.com.br
      LETSENCRYPT_HOST: api.beantest.devjosuehub.com.br
      LETSENCRYPT_EMAIL: josueneto.camargo@gmail.com
    depends_on:
      - database
    networks:
      - internal-network
    restart: always
  web: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      TZ: "America/Sao_Paulo"
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: www.beantest.devjosuehub.com.br, devjosuehub.com.br
      LETSENCRYPT_HOST: www.beantest.devjosuehub.com.br, devjosuehub.com.br
      LETSENCRYPT_EMAIL: josueneto.camargo@gmail.com
    networks:
      - internal-network
    restart: always
  database:
    image: postgres
    networks:
      - internal-network
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=2553218858"
      - "POSTGRES_DB=beantest"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

networks:
  internal-network:
    driver: bridge